name: Github Actions Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'PHP Version'
      run: php --version

    - name: 'Composer Install'
      run: composer install
